### ISSUE TITLE
Help menu entry

### ISSUE THREAD

**Issue by philpax** [SinisterRectus/JC2MP-Wingsuit#1]
Fire an event on ModuleLoad/ModuleUnload to register with the help menu

**Comment by SinisterRectus** [comment]
Added https://github.com/SinisterRectus/JC2MP-Wingsuit/commit/e7a6fa53de90647a9837805c815b1dc1a602dde4

**Comment by SinisterRectus** [comment]
Added https://github.com/SinisterRectus/JC2MP-Wingsuit/commit/e7a6fa53de90647a9837805c815b1dc1a602dde4
